package com.flower.anno.event;

public enum EventType {
  BEFORE_FLOW,
  AFTER_FLOW,
  BEFORE_STEP,
  AFTER_STEP,
  BEFORE_STEP_ITERATION,
  AFTER_STEP_ITERATION,
  BEFORE_EXEC,
  AFTER_EXEC,
  BEFORE_TRANSIT,
  AFTER_TRANSIT,
  FLOW_EXCEPTION
}
